### PR TITLE
Add Feed model, route, controller, etc.

### PR DESCRIPTION
**Pull request by AndrewLester**

### CODE REVIEW

**Comment by jdubpark** [comment]
What's `item_id` for? I see that `${course}_${section}` goes into both `section_full_code` and `item_id`, making `item_id` a duplicate (unless it's used differently for other feed items). If you are just assigning a UUID to it, `_id` already does that, so no need for it.

edit: so for example, would `item_id` be like `${section}_${assignmentID}` for assignment and different for others? Then it makes sense.

**Comment by jdubpark** [comment]
I changed `user_email` to `email` to keep the names in sync with other tables. I don't see `email` having name conflicts anytime soon.

**Comment by AndrewLester** [comment]
> What's `item_id` for? I see that `${course}_${section}` goes into both `section_full_code` and `item_id`, making `item_id` a duplicate (unless it's used differently for other feed items).

It is used differently for other feed items. It'll just be the item's primary key.

**Comment by jdubpark** [comment]
Looks all good. I will merge it within an hour if no additional comment is posted.

**Comment by AndrewLester** [comment]
> Looks all good. I will merge it within an hour if no additional comment is posted.

The UI stuff is almost done too... is token refreshing done by any chance? I'm not exactly sure how to work that.

**Comment by jdubpark** [comment]
I'm working on the auth JWT token system at the moment. Basically:

1. User logs in ==> Server sends back `access` and `refresh` JWT.
2. App stores `access` JWT in memory and `refresh` as HTTP-only, non-readable (by app's code) cookie.
2. User requests action with `access` JWT until before expiration.
3. User requests with expired `access` JWT ==> Server reads `refresh` token from the cookie & sends requested data AND the new `access` JWT
4. App stores the new `access` JWT in memory (so it'll need a catch function for response from server, checking if there is new `access` JWT to store).

**Comment by jdubpark** [comment]
Also, no need for `post_date` since if you look at the Feed insertion SQL:
```
    sql: 'INSERT INTO "Feeds" ("_id","email","section_full_code","item_id","type","body","post_date","action","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "_id","email","section_full_code","item_id","type","body","post_date","action","attachment_url","createdAt","updatedAt";',
    parameters: [
      '19656737-7ffc-43dd-9c0f-9e182bcb4fa8',
      'janedoe@example.com',
      'CS124_74477',
      'CS124_74477',
      2,
      'You subscribed to the section CS124_74477',
      '2021-08-04 06:02:03.492 +00:00',
      'created__new_subscriber',
      '2021-08-04 06:02:03.492 +00:00',
      '2021-08-04 06:02:03.492 +00:00'
    ]
```

You see that the last two columns (auto-generated by default) do what post_date intends to do. So we just need to rename `createdAt` as `postDate` when returning the data from DB.

**Pull request merged**
